<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE students [
        <!ELEMENT students (student*) >
        <!ELEMENT student (name,age,sex) >
        <!ELEMENT name (#PCDATA) >
        <!ELEMENT age (#PCDATA) >
        <!ELEMENT sex (#PCDATA) >
        <!ATTLIST student number ID #REQUIRED >
        ]> -->      <!--内部约束规则文件,少用-->
<!DOCTYPE students SYSTEM "student.dtd">    <!--以外部dtudent.dtd约束规则文件-->
<students>
    <student number="stu1">
        <name>罗木又</name>
        <age>22</age>
        <sex>男</sex>
    </student>
    <student number="stu2">
        <name>恰米</name>
        <age>20</age>
        <sex>女</sex>
    </student>
    <student number="stu3">
        <name>黄清华</name>
        <age>22</age>
        <sex>女</sex>
    </student>
</students>